language: swift
os: osx
osx_image: xcode11.3
xcode_sdk: iphonesimulator13.3

cache:
  directories:
    - Carthage

before_script:
  - bundle exec danger
  - brew update && brew bundle
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds
  - export PROJECT_DIR=$PWD && export PROJECT_NAME=CHMeetupApp && ./Scripts/natalie_generate
jobs:
  include:
# ==============================================================================
    - stage: test
      if: NOT (tag IS present)
      env: JOB=iOS Tests
      script:
        - xcodebuild -project CHMeetupApp.xcodeproj -scheme Debug -destination "platform=iOS Simulator,name=iPhone 8" -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" test | xcpretty -f `xcpretty-travis-formatter`
      after_success:
        - bash <(curl -s https://codecov.io/bash)
# ==============================================================================
